### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by bookercodes** [alexbooker/dotfiles#1]
- [x] Fix Nvm Zsh bug
- [x] Vpn does not auto-connect until I run `sudo ./etc/init.d/openvpn restart` which is dumb
- [ ] Make LastPass auto-complete
- [x] Add Vpn to i3blocks
- [ ] Fix i3 block volume bug
- [x] Float Spotify and Skype
- [ ] Open Windows on login
- [x] Force Windows to open on certain workspace?
- [x] Vim syntax highlighting lol
